// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	handler2 "github.com/hokkung/go-groceries/internal/handler"
	repository2 "github.com/hokkung/go-groceries/internal/repository"
	"github.com/hokkung/go-groceries/internal/server"
	service2 "github.com/hokkung/go-groceries/internal/service"
	server2 "github.com/hokkung/srv/server"
)

// Injectors from wire.go:

func InitializeApplication(context2 context.Context) (*ApplicationAPI, func(), error) {
	db, err := repository2.ProvideGormDB()
	if err != nil {
		return nil, nil, err
	}
	productRepository, cleanup, err := repository2.ProvideProductRepository(db)
	if err != nil {
		return nil, nil, err
	}
	productService := service2.ProvideProductService(productRepository)
	productHandler := handler2.ProvideProductHandler(productService)
	userRepository, cleanup2, err := repository2.ProvideUserRepository(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userService := service2.ProvideUserService(userRepository)
	userHandler := handler2.ProvideUserHandler(userService)
	serverCustomizer, cleanup3, err := server.ProvideCustomizer(productHandler, userHandler)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serverServer, cleanup4, err := server2.ProvideServer(serverCustomizer)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	applicationAPI := &ApplicationAPI{
		Server: serverServer,
	}
	return applicationAPI, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
