// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/hokkung/go-groceries/handler"
	"github.com/hokkung/go-groceries/repository"
	"github.com/hokkung/go-groceries/server"
	"github.com/hokkung/go-groceries/service"
	server2 "github.com/hokkung/srv/server"
)

// Injectors from wire.go:

func InitializeApplication() (*ApplicationAPI, error) {
	db, err := repository.ProvideGormDB()
	if err != nil {
		return nil, err
	}
	productRepository := repository.ProvideProductRepository(db)
	productService := service.ProvideProductService(productRepository)
	productHandler := handler.ProvideProductHandler(productService)
	serverCustomizer := server.ProvideCustomizer(productHandler)
	serverServer := server2.NewServer(serverCustomizer)
	applicationAPI := &ApplicationAPI{
		Server: serverServer,
	}
	return applicationAPI, nil
}
