// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/hokkung/go-groceries/handler"
	"github.com/hokkung/go-groceries/repository"
	"github.com/hokkung/go-groceries/server"
	"github.com/hokkung/go-groceries/service"
	server2 "github.com/hokkung/srv/server"
)

// Injectors from wire.go:

func InitializeApplication(context2 context.Context) (*ApplicationAPI, func(), error) {
	db, err := repository.ProvideGormDB()
	if err != nil {
		return nil, nil, err
	}
	productRepository, cleanup, err := repository.ProvideProductRepository(db)
	if err != nil {
		return nil, nil, err
	}
	productService := service.ProvideProductService(productRepository)
	productHandler := handler.ProvideProductHandler(productService)
	userRepository, cleanup2, err := repository.ProvideUserRepository(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userService := service.ProvideUserService(userRepository)
	userHandler := handler.ProvideUserHandler(userService)
	serverCustomizer, cleanup3, err := server.ProvideCustomizer(productHandler, userHandler)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serverServer, cleanup4, err := server2.ProvideServer(serverCustomizer)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	applicationAPI := &ApplicationAPI{
		Server: serverServer,
	}
	return applicationAPI, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
