name: Auto Assign Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Auto assign PR to the author
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.actor], // Automatically assigns the PR author
            });
